apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: jwt-generator-template
spec:
  entrypoint: jwt-generator
  templates:
    - name: jwt-generator
      inputs:
        parameters:
          - name: payload
          - name: secret
          - name: options
      container:
        image: bimspot/jwt-generator
        imagePullPolicy: IfNotPresent
        env:
          - name: PAYLOAD
            value: "{{inputs.parameters.payload}}"
          - name: SECRET
            value: "{{ inputs.parameters.secret }}"
          - name: OPTIONS
            value: "{{ inputs.parameters.options }}"