# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run.
on: [push, pull_request]
jobs:
  jwt-generator:
    name: JWT Generator
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action
        with:
          images: bimspot/jwt-generator
      
      - name: Build and push Docker image
        uses: docker/build-push-action
        with:
          working-directory: jwt
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}