# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run.
on:
  push:
    paths:
    - 'rabbit-message-publisher/**'
  pull_request:
    paths: 
    - 'rabbit-message-publisher/**'
jobs:
  rabbitmq-publisher:
    name: RabbitMQ Publisher
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: bimspot/rabbitmq-publisher
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value={{branch}}-{{sha}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: rabbit-message-publisher/Dockerfile
          context: ./rabbit-message-publisher
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}